{
	"entityName": "P1",
	"entityType": "player",
	"gravity": "1",
	"collidable": "true",
	"onCollide": {"default": "stop", "ai": "none","character": "destroy", "static":"none"},
	"sizeX": "0.8",
	"sizeY": "0.8",
	"moveSpeed": "1",
	"graphics": "assets/p1.png",
	"controls": {"UpDown": "jump","DownDown": "moveDown", "LeftDown": "moveLeft", "RightDown": "moveRight", "RightUp" : "stopMoveX", "LeftUp": "stopMoveX"}
} 